#created on: Jan 26, 2011
package com.db.itrac.rules.trade.tracking

import com.db.itrac.domain.trade.TpmlTrade
import com.db.itrac.domain.ItracStatus
import com.db.itrac.domain.UserAction
import com.db.itrac.rules.TradeUpdated
import com.oracle.coherence.patterns.messaging.MessagingSession

dialect "mvel" 

declare TradeUpdated
   @role(event)
   @timestamp(eventTime)
end

rule "Publish Trade"
ruleflow-group "tracking"
	when
	    $trade : TpmlTrade( itracStatus == ItracStatus.SENT_TO_BOOKING_SYSTEM) from entry-point "my-t1"
		$tradeEvent : TradeUpdated( itracId == $trade.itracId )
		$msgSession : MessagingSession ()				
	then    
		retract($tradeEvent);
		$msgSession.publishMessage("my-t1",$trade)	   
end